"""Schemas for the inspection report document."""
from datetime import datetime, timezone
from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field

from src.schemas.enums import ComplianceStatus


class ReportAudience(str, Enum):
    """Who is this report intended for. Drives tone and detail level."""
    EXECUTIVE = "executive"      # Leadership: short, business-impact framed
    OPERATIONAL = "operational"  # Facilities team: detailed, action-oriented
    REGULATORY = "regulatory"    # Auditors/inspectors: formal, citation-heavy


class ReportSection(BaseModel):
    """A single section of the report."""

    heading: Annotated[str, Field(min_length=3, max_length=200)]
    body_markdown: Annotated[str, Field(min_length=20, max_length=10000)]


class InspectionDocument(BaseModel):
    """A full inspection report generated by the Documentation Agent."""

    building_id: str
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    title: Annotated[str, Field(min_length=10, max_length=200)]
    audience: ReportAudience

    executive_summary: Annotated[str, Field(min_length=50, max_length=2000)]
    """Short narrative summary - the only thing some readers will read."""

    overall_status: ComplianceStatus
    headline_metrics: dict[str, int | str | float] = Field(default_factory=dict)
    """Key numbers: photos analyzed, critical findings, work orders, etc."""

    sections: list[ReportSection]
    """Detailed body content."""

    model_used: str

    output_path: str | None = None
    """Where the report was saved on disk. Set by the agent."""